// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search_inventory.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function matches(v, q) {
  if (!q) return true;
  const hay = [
    v.name,
    v.make,
    v.model,
    v.year?.toString(),
    v.exteriorColor,
    v.fuel,
    v.transmission,
    v.vin,
    v.stockNumber
  ].filter(Boolean).join(" ").toLowerCase();
  return q.toLowerCase().split(/\s+/).filter(Boolean).every((tok) => hay.includes(tok));
}
var search_inventory_default = defineTool({
  name: "search_inventory",
  title: "Search Middleman Motors inventory",
  description: "Search Middleman Motors' current pre-owned vehicle inventory by make, model, year, or keywords. Returns matching vehicles with price, mileage, and stock number.",
  inputSchema: {
    query: z.string().describe("Search terms, e.g. 'Toyota Camry', '2020 SUV', 'red truck'. Empty returns all.").default(""),
    max_price: z.number().describe("Optional maximum price in USD.").optional(),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, max_price, limit }) => {
    const env = globalThis.process?.env ?? {};
    const supabaseUrl = env.SUPABASE_URL;
    const anonKey = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "";
    const res = await fetch(`${supabaseUrl}/functions/v1/waynereaves-inventory`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...anonKey ? { Authorization: `Bearer ${anonKey}`, apikey: anonKey } : {}
      },
      body: JSON.stringify({ action: "list" })
    });
    if (!res.ok) {
      const text = await res.text();
      return {
        content: [{ type: "text", text: `Inventory feed error (${res.status}): ${text}` }],
        isError: true
      };
    }
    const data = await res.json();
    const all = data.vehicles ?? [];
    const filtered = all.filter((v) => matches(v, query ?? "")).filter((v) => max_price ? Number(v.price ?? 0) <= max_price : true).slice(0, limit);
    if (filtered.length === 0) {
      return {
        content: [
          {
            type: "text",
            text: `No vehicles match "${query}"${max_price ? ` under $${max_price}` : ""}. Total in inventory: ${all.length}.`
          }
        ],
        structuredContent: { total: all.length, results: [] }
      };
    }
    const lines = filtered.map(
      (v) => `\u2022 ${v.name ?? `${v.year ?? ""} ${v.make ?? ""} ${v.model ?? ""}`.trim()} \u2014 $${Number(v.price ?? 0).toLocaleString()} \u2014 ${v.mileage ?? "?"} mi \u2014 Stock #${v.stockNumber ?? "?"}`
    );
    return {
      content: [
        {
          type: "text",
          text: `Found ${filtered.length} of ${all.length} vehicles:
${lines.join("\n")}

View the full lot at https://www.middlemanmotors.com/inventory`
        }
      ],
      structuredContent: { total: all.length, count: filtered.length, results: filtered }
    };
  }
});

// src/lib/mcp/tools/get_dealership_info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var INFO = {
  name: "Middleman Motors",
  tagline: "Quality pre-owned vehicles with transparent pricing",
  website: "https://www.middlemanmotors.com",
  service_area: ["Georgia", "Virginia"],
  certifications: ["Minority-Owned Business", "African American-Owned Business", "GIADA Member"],
  services: [
    "Pre-owned vehicle sales",
    "150-point vehicle inspection",
    "Financing & credit applications",
    "Government & fleet contracting",
    "Vehicle comparison tool"
  ],
  policies: {
    inspection: "Every vehicle undergoes a 150-point inspection before sale.",
    pre_qualifying_fee: "A non-refundable fee of $100 is required to obtain a soft credit report for evaluating eligibility for vehicle purchase and financing. This does not impact your credit score."
  },
  pages: {
    inventory: "https://www.middlemanmotors.com/inventory",
    apply: "https://www.middlemanmotors.com/apply",
    government: "https://www.middlemanmotors.com/government-contracting",
    partners: "https://www.middlemanmotors.com/partners"
  }
};
var get_dealership_info_default = defineTool2({
  name: "get_dealership_info",
  title: "Get Middleman Motors dealership info",
  description: "Return general information about Middleman Motors: services, service area, certifications, inspection policy, and key page URLs.",
  inputSchema: {
    section: z2.enum(["all", "services", "policies", "pages", "certifications"]).default("all").describe("Which section of the dealership info to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ section }) => {
    const data = section === "all" ? INFO : section === "services" ? { services: INFO.services } : section === "policies" ? { policies: INFO.policies } : section === "pages" ? { pages: INFO.pages } : { certifications: INFO.certifications };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/list_recent_leads.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser(token) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "";
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_leads_default = defineTool3({
  name: "list_recent_leads",
  title: "List recent Middleman Motors leads",
  description: "Return the most recent customer leads. Admin/finance access only. Sensitive customer data \u2014 do not share externally.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Max leads to return (1-50)."),
    status: z3.string().optional().describe("Optional status filter (e.g. 'new', 'contacted').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = supabaseForUser(ctx.getToken());
    let q = sb.from("leads").select("id, created_at, name, email, phone, source, program_tags, status, message").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Query failed: ${error.message}` }],
        isError: true
      };
    }
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No leads found." }], structuredContent: { leads: [] } };
    }
    const lines = data.map(
      (l) => `\u2022 ${l.name ?? "\u2014"} <${l.email ?? "no email"}> \xB7 ${l.phone ?? "no phone"} \xB7 ${l.source ?? "?"} \xB7 ${l.status ?? "new"} \xB7 ${new Date(l.created_at).toLocaleDateString()}`
    );
    return {
      content: [{ type: "text", text: `${data.length} recent leads:
${lines.join("\n")}` }],
      structuredContent: { leads: data }
    };
  }
});

// src/lib/mcp/tools/list_credit_applications.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser2(token) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "";
  return createClient2(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_credit_applications_default = defineTool4({
  name: "list_credit_applications",
  title: "List Middleman Motors credit applications",
  description: "Return recent credit applications. Admin/finance access only. Sensitive PII \u2014 do not share externally. Redacts SSN and DL numbers.",
  inputSchema: {
    limit: z4.number().int().min(1).max(50).default(10).describe("Max applications to return (1-50)."),
    status: z4.string().optional().describe("Optional status filter (e.g. 'pending', 'approved', 'declined').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = supabaseForUser2(ctx.getToken());
    let q = sb.from("credit_applications").select("id, created_at, status, channel, first_name, last_name, email, phone, city, state, housing_status, housing_payment").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Query failed: ${error.message}` }],
        isError: true
      };
    }
    if (!data || data.length === 0) {
      return {
        content: [{ type: "text", text: "No credit applications found." }],
        structuredContent: { applications: [] }
      };
    }
    const lines = data.map(
      (a) => `\u2022 ${a.first_name ?? ""} ${a.last_name ?? ""} <${a.email ?? "no email"}> \xB7 ${a.city ?? "?"}, ${a.state ?? "?"} \xB7 ${a.status ?? "pending"} \xB7 ${new Date(a.created_at).toLocaleDateString()}`
    );
    return {
      content: [{ type: "text", text: `${data.length} credit applications:
${lines.join("\n")}` }],
      structuredContent: { applications: data }
    };
  }
});

// src/lib/mcp/tools/list_deals_in_pipeline.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser3(token) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const anon = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY ?? "";
  return createClient3(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_deals_in_pipeline_default = defineTool5({
  name: "list_deals_in_pipeline",
  title: "List deals in the sales pipeline",
  description: "Return active deals from the sales pipeline. Admin/finance access only. Shows stage, vehicle, customer, and sale price.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(10).describe("Max deals to return (1-50)."),
    stage: z5.string().optional().describe("Optional pipeline stage filter (e.g. 'new', 'financing', 'closed').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, stage }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const sb = supabaseForUser3(ctx.getToken());
    let q = sb.from("deals").select(
      "id, created_at, stage, vehicle_year, vehicle_make, vehicle_model, vehicle_stock_number, sale_price, customer_name, customer_email, customer_phone"
    ).order("created_at", { ascending: false }).limit(limit);
    if (stage) q = q.eq("stage", stage);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: `Query failed: ${error.message}` }],
        isError: true
      };
    }
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: "No deals found." }], structuredContent: { deals: [] } };
    }
    const lines = data.map(
      (d) => `\u2022 [${d.stage ?? "?"}] ${d.vehicle_year ?? ""} ${d.vehicle_make ?? ""} ${d.vehicle_model ?? ""} (Stock #${d.vehicle_stock_number ?? "?"}) \u2014 ${d.customer_name ?? "?"} \u2014 $${Number(d.sale_price ?? 0).toLocaleString()}`
    );
    return {
      content: [{ type: "text", text: `${data.length} deals:
${lines.join("\n")}` }],
      structuredContent: { deals: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gvezvcyfoyxzktkzfvuw";
var mcp_default = defineMcp({
  name: "middleman-motors-mcp",
  title: "Middleman Motors",
  version: "0.2.0",
  instructions: "Tools for Middleman Motors, a pre-owned car dealership serving Georgia and Virginia.\n\nPublic tools (no auth): `search_inventory`, `get_dealership_info`.\n\nAuthenticated tools (admin/finance staff only): `list_recent_leads`, `list_credit_applications`, `list_deals_in_pipeline`. These return sensitive customer PII \u2014 never share externally.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_inventory_default,
    get_dealership_info_default,
    list_recent_leads_default,
    list_credit_applications_default,
    list_deals_in_pipeline_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
